//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8922
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.8922.
// 
#pragma warning disable 1591

namespace PraxairComunicaciones.WSPraxair {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataAccessSoap", Namespace="http://tempuri.org/")]
    public partial class DataAccess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFechaSistemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDatosCargaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmarCargaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendDatosOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadArchivoPDFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataAccess() {
            this.Url = global::PraxairComunicaciones.Properties.Settings.Default.PraxairComunicaciones_WSPraxair_DataAccess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFechaSistemaCompletedEventHandler GetFechaSistemaCompleted;
        
        /// <remarks/>
        public event GetDatosCargaCompletedEventHandler GetDatosCargaCompleted;
        
        /// <remarks/>
        public event ConfirmarCargaCompletedEventHandler ConfirmarCargaCompleted;
        
        /// <remarks/>
        public event SendDatosCompletedEventHandler SendDatosCompleted;
        
        /// <remarks/>
        public event UploadArchivoPDFCompletedEventHandler UploadArchivoPDFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFechaSistema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFechaSistema() {
            object[] results = this.Invoke("GetFechaSistema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFechaSistemaAsync() {
            this.GetFechaSistemaAsync(null);
        }
        
        /// <remarks/>
        public void GetFechaSistemaAsync(object userState) {
            if ((this.GetFechaSistemaOperationCompleted == null)) {
                this.GetFechaSistemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFechaSistemaOperationCompleted);
            }
            this.InvokeAsync("GetFechaSistema", new object[0], this.GetFechaSistemaOperationCompleted, userState);
        }
        
        private void OnGetFechaSistemaOperationCompleted(object arg) {
            if ((this.GetFechaSistemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFechaSistemaCompleted(this, new GetFechaSistemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDatosCarga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDatosCarga(string sTerminal, int iCodigoProceso, int iCodigoPrograma) {
            object[] results = this.Invoke("GetDatosCarga", new object[] {
                        sTerminal,
                        iCodigoProceso,
                        iCodigoPrograma});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDatosCargaAsync(string sTerminal, int iCodigoProceso, int iCodigoPrograma) {
            this.GetDatosCargaAsync(sTerminal, iCodigoProceso, iCodigoPrograma, null);
        }
        
        /// <remarks/>
        public void GetDatosCargaAsync(string sTerminal, int iCodigoProceso, int iCodigoPrograma, object userState) {
            if ((this.GetDatosCargaOperationCompleted == null)) {
                this.GetDatosCargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatosCargaOperationCompleted);
            }
            this.InvokeAsync("GetDatosCarga", new object[] {
                        sTerminal,
                        iCodigoProceso,
                        iCodigoPrograma}, this.GetDatosCargaOperationCompleted, userState);
        }
        
        private void OnGetDatosCargaOperationCompleted(object arg) {
            if ((this.GetDatosCargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatosCargaCompleted(this, new GetDatosCargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmarCarga", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ConfirmarCarga(string sTerminal, int iCodigoProceso, int iCodigoPrograma) {
            this.Invoke("ConfirmarCarga", new object[] {
                        sTerminal,
                        iCodigoProceso,
                        iCodigoPrograma});
        }
        
        /// <remarks/>
        public void ConfirmarCargaAsync(string sTerminal, int iCodigoProceso, int iCodigoPrograma) {
            this.ConfirmarCargaAsync(sTerminal, iCodigoProceso, iCodigoPrograma, null);
        }
        
        /// <remarks/>
        public void ConfirmarCargaAsync(string sTerminal, int iCodigoProceso, int iCodigoPrograma, object userState) {
            if ((this.ConfirmarCargaOperationCompleted == null)) {
                this.ConfirmarCargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmarCargaOperationCompleted);
            }
            this.InvokeAsync("ConfirmarCarga", new object[] {
                        sTerminal,
                        iCodigoProceso,
                        iCodigoPrograma}, this.ConfirmarCargaOperationCompleted, userState);
        }
        
        private void OnConfirmarCargaOperationCompleted(object arg) {
            if ((this.ConfirmarCargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmarCargaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendDatos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendDatos(string sTerminal, int iCodigoPrograma, int iCodigoProceso, string sDatosEnviados) {
            this.Invoke("SendDatos", new object[] {
                        sTerminal,
                        iCodigoPrograma,
                        iCodigoProceso,
                        sDatosEnviados});
        }
        
        /// <remarks/>
        public void SendDatosAsync(string sTerminal, int iCodigoPrograma, int iCodigoProceso, string sDatosEnviados) {
            this.SendDatosAsync(sTerminal, iCodigoPrograma, iCodigoProceso, sDatosEnviados, null);
        }
        
        /// <remarks/>
        public void SendDatosAsync(string sTerminal, int iCodigoPrograma, int iCodigoProceso, string sDatosEnviados, object userState) {
            if ((this.SendDatosOperationCompleted == null)) {
                this.SendDatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendDatosOperationCompleted);
            }
            this.InvokeAsync("SendDatos", new object[] {
                        sTerminal,
                        iCodigoPrograma,
                        iCodigoProceso,
                        sDatosEnviados}, this.SendDatosOperationCompleted, userState);
        }
        
        private void OnSendDatosOperationCompleted(object arg) {
            if ((this.SendDatosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendDatosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadArchivoPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadArchivoPDF(string nombreArchivo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] bytes) {
            object[] results = this.Invoke("UploadArchivoPDF", new object[] {
                        nombreArchivo,
                        bytes});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadArchivoPDFAsync(string nombreArchivo, byte[] bytes) {
            this.UploadArchivoPDFAsync(nombreArchivo, bytes, null);
        }
        
        /// <remarks/>
        public void UploadArchivoPDFAsync(string nombreArchivo, byte[] bytes, object userState) {
            if ((this.UploadArchivoPDFOperationCompleted == null)) {
                this.UploadArchivoPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadArchivoPDFOperationCompleted);
            }
            this.InvokeAsync("UploadArchivoPDF", new object[] {
                        nombreArchivo,
                        bytes}, this.UploadArchivoPDFOperationCompleted, userState);
        }
        
        private void OnUploadArchivoPDFOperationCompleted(object arg) {
            if ((this.UploadArchivoPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadArchivoPDFCompleted(this, new UploadArchivoPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    public delegate void GetFechaSistemaCompletedEventHandler(object sender, GetFechaSistemaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFechaSistemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFechaSistemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    public delegate void GetDatosCargaCompletedEventHandler(object sender, GetDatosCargaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatosCargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatosCargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    public delegate void ConfirmarCargaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    public delegate void SendDatosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    public delegate void UploadArchivoPDFCompletedEventHandler(object sender, UploadArchivoPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.8922")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadArchivoPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadArchivoPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591