'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.7905
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Desktop.Framework.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _18_subAccounts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_18_subAccounts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AddTable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddTable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuilderDialog_movedown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuilderDialog_movedown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuilderDialog_movedown1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuilderDialog_movedown1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_export2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_export2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property database_import() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database_import", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit_Undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_Undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EditInformation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditInformation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EditInformation1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditInformation1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExportToDatabase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportToDatabase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExportToFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportToFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Filter2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Filter2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gear_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GoToDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoToDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GoToUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoToUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GoToUp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoToUp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_16_4500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_16_4500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_16_securityrole() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_16_securityrole", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_18_secure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_18_secure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ImportFromDatabase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImportFromDatabase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ImportFromFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImportFromFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewDocument() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewDocument", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewWindow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewWindow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewWindow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewWindow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OpenFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RefreshDocView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREATE TABLE [Perfiles](
        '''	[IdPerfil] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        '''	[Nombre] [nvarchar](100) NOT NULL,
        '''	[Activo] [bit] NOT NULL,
        '''	[Sistema] [bit] NOT NULL);
        '''CREATE TABLE [Empresas](
        '''	[IdEmpresa] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        '''	[NIT] [nvarchar](15) NOT NULL,
        '''	[NombreCorto] [nvarchar](50) NOT NULL,
        '''	[NombreCompleto] [nvarchar](100) NOT NULL,
        '''	[Direccion] [nvarchar](200) NULL,
        '''	[Ciudad] [nvarchar](50) NULL,
        '''	[Pais] [nvarchar](50) NULL,
        '''	[Telefono] [nvarchar](30) NULL,
        '''	[Fax [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ScriptSQLMobile() As String
            Get
                Return ResourceManager.GetString("ScriptSQLMobile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SET ANSI_NULLS ON;
        '''SET QUOTED_IDENTIFIER ON;
        '''IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[Perfiles]&apos;) AND type in (N&apos;U&apos;))
        '''BEGIN
        '''CREATE TABLE [dbo].[Perfiles](
        '''	[IdPerfil] [int] IDENTITY(1,1) NOT NULL,
        '''	[Nombre] [nvarchar](100) NOT NULL,
        '''	[Activo] [bit] NOT NULL,
        '''	[Sistema] [bit] NOT NULL,
        ''' CONSTRAINT [PK_Perfiles] PRIMARY KEY (IdPerfil))
        '''END
        '''SET ANSI_NULLS ON;
        '''SET QUOTED_IDENTIFIER ON;
        '''IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo]. [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ScriptSQLServer() As String
            Get
                Return ResourceManager.GetString("ScriptSQLServer", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sdhcinst_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sdhcinst_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Task() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Task", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
