'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8922
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8922.
'
Namespace wsNiso
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WebService1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WebService1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://201.234.244.37/WsNiso/WebService1.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarEstadoRegistro", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActualizarEstadoRegistro(ByVal id As Integer, ByVal estado As String, ByVal usrid As Integer) As Boolean
            Dim results() As Object = Me.Invoke("ActualizarEstadoRegistro", New Object() {id, estado, usrid})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginActualizarEstadoRegistro(ByVal id As Integer, ByVal estado As String, ByVal usrid As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ActualizarEstadoRegistro", New Object() {id, estado, usrid}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndActualizarEstadoRegistro(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarGestion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActualizarGestion(ByVal id As Integer, ByVal gestionRealizada As String, ByVal aplicaSqr As Boolean, ByVal IdSqr As String, ByVal usrId As Integer) As Boolean
            Dim results() As Object = Me.Invoke("ActualizarGestion", New Object() {id, gestionRealizada, aplicaSqr, IdSqr, usrId})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginActualizarGestion(ByVal id As Integer, ByVal gestionRealizada As String, ByVal aplicaSqr As Boolean, ByVal IdSqr As String, ByVal usrId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ActualizarGestion", New Object() {id, gestionRealizada, aplicaSqr, IdSqr, usrId}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndActualizarGestion(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarPregunta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ActualizarPregunta(ByVal rst As Respuesta) As Boolean
            Dim results() As Object = Me.Invoke("ActualizarPregunta", New Object() {rst})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginActualizarPregunta(ByVal rst As Respuesta, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ActualizarPregunta", New Object() {rst}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndActualizarPregunta(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlmacenarPregunta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AlmacenarPregunta(ByVal rst As Respuesta) As Boolean
            Dim results() As Object = Me.Invoke("AlmacenarPregunta", New Object() {rst})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginAlmacenarPregunta(ByVal rst As Respuesta, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AlmacenarPregunta", New Object() {rst}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndAlmacenarPregunta(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMail", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarMail(ByVal [to] As String, ByVal mensaje As String) As Boolean
            Dim results() As Object = Me.Invoke("EnviarMail", New Object() {[to], mensaje})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginEnviarMail(ByVal [to] As String, ByVal mensaje As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EnviarMail", New Object() {[to], mensaje}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndEnviarMail(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCliente", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCliente(ByVal CodigoCliente As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetCliente", New Object() {CodigoCliente})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetCliente(ByVal CodigoCliente As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCliente", New Object() {CodigoCliente}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetCliente(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClienteOtro", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetClienteOtro(ByVal CodigoCliente As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetClienteOtro", New Object() {CodigoCliente})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetClienteOtro(ByVal CodigoCliente As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetClienteOtro", New Object() {CodigoCliente}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetClienteOtro(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEstadosRegistros", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEstadosRegistros() As EstadoRegistro()
            Dim results() As Object = Me.Invoke("GetEstadosRegistros", New Object(-1) {})
            Return CType(results(0),EstadoRegistro())
        End Function
        
        '''<remarks/>
        Public Function BeginGetEstadosRegistros(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetEstadosRegistros", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetEstadosRegistros(ByVal asyncResult As System.IAsyncResult) As EstadoRegistro()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),EstadoRegistro())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrigenes", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOrigenes() As Origen()
            Dim results() As Object = Me.Invoke("GetOrigenes", New Object(-1) {})
            Return CType(results(0),Origen())
        End Function
        
        '''<remarks/>
        Public Function BeginGetOrigenes(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetOrigenes", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetOrigenes(ByVal asyncResult As System.IAsyncResult) As Origen()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Origen())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPreguntas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPreguntas() As Pregunta()
            Dim results() As Object = Me.Invoke("GetPreguntas", New Object(-1) {})
            Return CType(results(0),Pregunta())
        End Function
        
        '''<remarks/>
        Public Function BeginGetPreguntas(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPreguntas", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetPreguntas(ByVal asyncResult As System.IAsyncResult) As Pregunta()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Pregunta())
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRespuestas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRespuestas(ByVal fechaIni As Date, ByVal FechaFin As Date, ByVal estado As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetRespuestas", New Object() {fechaIni, FechaFin, estado})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetRespuestas(ByVal fechaIni As Date, ByVal FechaFin As Date, ByVal estado As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetRespuestas", New Object() {fechaIni, FechaFin, estado}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetRespuestas(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSeguimiento", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSeguimiento(ByVal id As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetSeguimiento", New Object() {id})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetSeguimiento(ByVal id As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSeguimiento", New Object() {id}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetSeguimiento(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTipoRespuestas", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTipoRespuestas(ByVal preg As Pregunta) As Respuesta()
            Dim results() As Object = Me.Invoke("GetTipoRespuestas", New Object() {preg})
            Return CType(results(0),Respuesta())
        End Function
        
        '''<remarks/>
        Public Function BeginGetTipoRespuestas(ByVal preg As Pregunta, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTipoRespuestas", New Object() {preg}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetTipoRespuestas(ByVal asyncResult As System.IAsyncResult) As Respuesta()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Respuesta())
        End Function
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Respuesta
        
        '''<remarks/>
        Public ID As Integer
        
        '''<remarks/>
        Public CODI_CLI As String
        
        '''<remarks/>
        Public ID_PREGUNTA As Integer
        
        '''<remarks/>
        Public ID_RESPUESTA As Integer
        
        '''<remarks/>
        Public FECHA_RESPUESTA As Date
        
        '''<remarks/>
        Public CORREO_ELECTRONICO As String
        
        '''<remarks/>
        Public TELEFONO As String
        
        '''<remarks/>
        Public NOMBRE As String
        
        '''<remarks/>
        Public ESTADO_REGISTRO As String
        
        '''<remarks/>
        Public USRID_GESTION As String
        
        '''<remarks/>
        Public FECHA_GESTION As Date
        
        '''<remarks/>
        Public ID_ORIGEN As String
        
        '''<remarks/>
        Public GestionRealizada As String
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Pregunta
        
        '''<remarks/>
        Public ID_PREGUNTA As Integer
        
        '''<remarks/>
        Public DESCRIPCION As String
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Origen
        
        '''<remarks/>
        Public ID_ORIGEN As Integer
        
        '''<remarks/>
        Public NOMBRE As String
    End Class
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EstadoRegistro
        
        '''<remarks/>
        Public id_estado As String
        
        '''<remarks/>
        Public descripcion As String
    End Class
End Namespace
